title: Print Bill Master
description: "A Web-Based Printer Management Application Built for Scale."
theme: just-the-docs

email: houstonhvrd@gmail.com
url: https://houstonlws.github.io
baseurl: /PBM

aux_links:
  PBM GitHub: https://github.com/houstonlws/PBM

just-the-docs:
  logo: /assets/images/logo.png
  search_enabled: true

plugins:
  - jekyll-remote-theme
