title: Print Bill Master
description: "A Web-Based Printer Management Application Built for Scale."
theme: just-the-docs

email: houstonhvrd@gmail.com
url: https://houstonlws.github.io
baseurl: /portfolio/pbm

aux_links:
  PBM GitHub: https://github.com/houstonlws/PrintBillMaster
