name: Deploy Jekyll site to Pages

on:
  # Trigger on pushes to the main branch
  push:
    branches: ["gh-pages"]

  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build the Jekyll site
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup Ruby and Bundler
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # Caches installed gems

      # Install dependencies
      - name: Install Dependencies
        run: |
          bundle install
        env:
          JEKYLL_ENV: production

      # Build the site with Jekyll
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # Upload the built `_site` folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
