name: Deploy Jekyll site with custom version

on:
  push:
    branches: ["gh-pages"]  # Trigger on pushes to the main branch
  workflow_dispatch:    # Allow manual runs

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
