name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ['gh-pages']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bundle install

      # Step 4: Build Jekyll site (specifying the docs folder as source)
      - name: Build Jekyll site
        run: bundle exec jekyll build --source ./docs --destination ./docs/_site
        env:
          JEKYLL_ENV: production

      # Step 5: Upload artifact (specifying the built site in docs/_site)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
